acts_external_login_auth:
    path: /login/{service}

acts_external_login_entry:
    path: /redirect/{service}

acts_external_login_test_login:
    path: /test-login/{service}
    defaults: { _controller: ActsExternalLoginBundle:Default:testLogin }